Revert "Add support for `getrandom`."
This reverts commit d0f1d69ba32ab86b3ea55c534f2fa8bd3e5f00ba.

Reason for revert: Breaks build in Chromium and elsewhere:

  src/third_party/lss/linux_syscall_support.h:3682:7: error: use of undeclared identifier '__NR_ssize_t'

Change-Id: I227350d8fa9405e7b65bbeee48ae72754b5dfad0
Reviewed-on: https://chromium-review.googlesource.com/c/linux-syscall-support/+/2212610
Reviewed-by: Mike Frysinger <vapier@chromium.org>